apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsix-registry
  namespace: devspaces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsix-registry
  template:
    metadata:
      labels:
        app: vsix-registry
    spec:
      containers:
        - name: nginx
          image: docker.io/nginxinc/nginx-unprivileged:1.25
          ports:
            - containerPort: 8080
          env:
            - name: NGINX_ENVSUBST_OUTPUT_DIR
              value: /tmp
          volumeMounts:
            - name: vsix-storage
              mountPath: /usr/share/nginx/html
            - name: cache
              mountPath: /tmp/cache
      volumes:
        - name: vsix-storage
          persistentVolumeClaim:
            claimName: vsix-registry-pvc
        - name: cache
          emptyDir: {}
